export const LOG_IN = "LOGIN"
export const LOG_OUT = "LOGOUT"
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES"
export const ADD_TO_CART = "ADD_TO_CART"
export const BOOKS_LOADED = "BOOKS_LOADED"
export const FILTERED_BOOKS_LOADED = "FILTERED_BOOKS_LOADED"